# Generated by Django 3.2.16 on 2022-12-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20221225_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='Email',
        ),
    ]
