# Generated by Django 3.2.16 on 2022-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20221225_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
