# Generated by Django 3.2.16 on 2022-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_massage_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
