# Generated by Django 3.2.16 on 2022-12-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_auto_20221227_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='date_created',
        ),
    ]
