# Generated by Django 3.2.16 on 2022-12-27 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_remove_massage_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
